#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

if [ ! -x "$(command -v nginx)" ]; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

sudo service nginx start
