#!/usr/bin/env bash
#Configures my Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

if [ ! -x "$(command -v nginx)" ]; then
    sudo apt-get update
    sudo apt-get install -y nginx
    sudo sed 's#server_name _;#server_name _;\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t\troot /var/www/html;\n\t}\n#g' /etc/nginx/sites-available/default
    sudo service nginx restart
    return
fi

sudo sed 's#server_name _;#server_name _;\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t\troot /var/www/html;\n\t}\n#g' /etc/nginx/sites-available/default

sudo service nginx restart
