#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"
# Configures my Nginx server so that /redirect_me is redirecting to another page.
# Configure Nginx so that its HTTP response contains a custom header

if [ ! -x "$(command -v nginx)" ]; then
    sudo apt-get -y update
    sudo apt-get -y install nginx
fi

echo "Hello World" | sudo tee /var/www/html/index

sudo sed -i 's#server_name _;#server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\tadd_header X-Served-By $hostname;\n#g' /etc/nginx/sites-available/default

sudo service nginx restart
