#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Makes sure that HAproxy can be managed via an init script
# Makes sure that servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.

if [ ! -x "$(command -v haproxy)" ]; then
    sudo apt-get -y update
    sudo apt-get -y install haproxy
fi

echo "
frontend 101877-lb-01
        bind *:80
        mode http
        default_backend server

backend server
        balance roundrobin
        mode http
        server 101877-web-01 54.237.112.44:80 check
        server 101877-web-02 35.175.63.68:80 check" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
