#!/usr/bin/env bash
:<<'COMMENT'
Bash script that displays listening ports

Requirements:
- Only shows listening sockets
- Shows the PID and name of the program to which each socket belongs
COMMENT
netstat -lp
