#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.

# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

for num in {1..100}
do
  if (( num % 15 == 0 ))
  then
    printf "FizzBuzz\n"
  elif (( num % 3 == 0 ))
  then
    printf "Fizz\n"
  elif (( num % 5 == 0 ))
  then
    printf "Buzz\n"
  else
    printf "%s" "$num"
  fi
done
