#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.

# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

x=1
while [ $x -le 100 ]
do
        if [ $(( $x % 15 )) -eq 0 ]
        then
                printf "FizzBuzz\n"
        elif [ $(( $x % 3 )) -eq 0 ]
        then
                printf "Fizz\n"
        elif [ $(( $x % 5 )) -eq 0 ]
        then
                printf "Buzz\n"
        else
                printf "%s\n" "$x"
        fi
        (( x++ ))
done
