#!/usr/bin/env bash
# This is a bash script that loops from 1 to 10
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
# Using a while loop
x=1
while [ $x -le 10 ];
do
	if [ $x == 4 ]
	then
		printf "bad luck\n"
	elif [ $x == 8 ]
	then
		printf "good luck\n"
	else
		printf "Best School\n"
	fi
	(( x++ ))
done
