#!/usr/bin/env bash
# Install firewalls, block any incoming request except on 22, 443 and 80 ports
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
