#!/usr/bin/env bash
 # Fix this container so that Nginx is running as the nginx user.
 # Bash script that runs nginx webserver as nginx and also 
 # Configures nginx to listen to port 8080
 sed -i 's/80/8080/g' /etc/nginx/sites-available/default
 chmod 644 /etc/nginx/nginx.conf
 sudo -u nginx service nginx restart
